### ISSUE TITLE
Error: Could not locate the bindings file

### ISSUE THREAD

**Issue by lrkwz** [carsondarling/bcrypt-cli#2]
What's wrong here?

```
lrkwz:~/ $ npm version
{ npm: '2.15.11',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '56.1',
  modules: '46',
  node: '4.6.2',
  openssl: '1.0.2j',
  uv: '1.9.1',
  v8: '4.5.103.42',
  zlib: '1.2.8' }
lrkwz:~$ sudo npm install -g @carsondarling/bcrypt-cli
npm WARN cannot run in wd bcrypt@0.8.7 node-gyp rebuild (wd=/usr/lib/node_modules/@carsondarling/bcrypt-cli/node_modules/bcrypt)
/usr/bin/debcrypt -> /usr/lib/node_modules/@carsondarling/bcrypt-cli/bin/debcrypt.js
/usr/bin/bcrypt -> /usr/lib/node_modules/@carsondarling/bcrypt-cli/bin/bcrypt.js
@carsondarling/bcrypt-cli@1.1.0 /usr/lib/node_modules/@carsondarling/bcrypt-cli
├── bcrypt@0.8.7 (bindings@1.2.1, nan@2.3.5)
└── argparse@1.0.2 (sprintf-js@1.0.3, lodash@3.10.1)
lrkwz:~/ $ bcrypt
/usr/lib/node_modules/@carsondarling/bcrypt-cli/node_modules/bcrypt/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /usr/lib/node_modules/@carsondarling/bcrypt-cli/node_modules/bcrypt/build/bcrypt_lib.node
 → /usr/lib/node_modules/@carsondarling/bcrypt-cli/node_modules/bcrypt/build/Debug/bcrypt_lib.node
 → /usr/lib/node_modules/@carsondarling/bcrypt-cli/node_modules/bcrypt/build/Release/bcrypt_lib.node
 → /usr/lib/node_modules/@carsondarling/bcrypt-cli/node_modules/bcrypt/out/Debug/bcrypt_lib.node
 → /usr/lib/node_modules/@carsondarling/bcrypt-cli/node_modules/bcrypt/Debug/bcrypt_lib.node
 → /usr/lib/node_modules/@carsondarling/bcrypt-cli/node_modules/bcrypt/out/Release/bcrypt_lib.node
 → /usr/lib/node_modules/@carsondarling/bcrypt-cli/node_modules/bcrypt/Release/bcrypt_lib.node
 → /usr/lib/node_modules/@carsondarling/bcrypt-cli/node_modules/bcrypt/build/default/bcrypt_lib.node
 → /usr/lib/node_modules/@carsondarling/bcrypt-cli/node_modules/bcrypt/compiled/4.2.1/linux/x64/bcrypt_lib.node
    at bindings (/usr/lib/node_modules/@carsondarling/bcrypt-cli/node_modules/bcrypt/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/usr/lib/node_modules/@carsondarling/bcrypt-cli/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/lib/node_modules/@carsondarling/bcrypt-cli/bin/bcrypt.js:3:14)
    at Module._compile (module.js:435:26)

**Comment by carsondarling** [comment]
I haven't seen this error before. What OS are you on? Can you try installing bcrypt on it's own:

```bash
npm install -g bcrypt
```

And see if you get the same error?

**Comment by lrkwz** [comment]
I'm running this on ubuntu 16.04 LTS

I've installed bcrypt AND bcrypt-cli

This script runs smoothly

    var bcrypt = require('bcrypt');
    const saltRounds = 10;
    const myPlaintextPassword = 's0/\/\P4$$w0rD';
    bcrypt.genSalt(saltRounds, function(err, salt) {
        bcrypt.hash(myPlaintextPassword, salt, function(err, hash) {
            // Store hash in your password DB.
        });
    });


[sorry it's just a brainless cut and paste from https://www.npmjs.com/package/bcrypt]

**Comment by carsondarling** [comment]
Alright, I think this has to do with running node with elevated privileges, as described in [this issue](https://github.com/npm/npm/issues/3497).

For two work arounds:

1. (preferred) Try installing npm so that it doesn't need the sudo command to install a package.
2. Use the `--unsafe-perm` flag when installing:

```bash
sudo npm install --unsafe-perm -g @carsondarling/bcrypt-cli
```

**Comment by carsondarling** [comment]
A third option for a workaround is to:

1. Install `node-gyp` via npm (`npm install -g node-gyp`)
2. Go to the global `node_modules` folder (e.g. `/usr/local/lib/node_modues`)
3. `cd @carsondarling/bcrypt-cli/node_modules/bcrypt`
4. `node-gyp rebuild`

That seemed to repair things on the Ubuntu system I tested, but your mileage may vary.

As this seems to be install-dependent and not an issue with the package itself, I'm going to close this issue. @lrkwz if you can't get it working, feel free to reopen!

**Comment by lrkwz** [comment]
Yes this worked for me as well!
It should be added to install instructions isn't it?

**Comment by carsondarling** [comment]
Yeah, it definitely could be. Feel free to make a PR!
