### ISSUE TITLE
debcrypt never matches

### ISSUE THREAD

**Issue by SSTPIERRE2** [carsondarling/bcrypt-cli#7]
Hi there, today I installed this package hoping it can help me hash passwords in the CLI. However, whenever I use the commands like so:
```
bcrypt
> Raw text: test
> {{hash}}
debcrypt '{{hash}}' test
```
I get the same output "Hash does not match.". No matter which format I try as suggested in the readme, it never matches. I'm on Mac OSX, all I did was install the package globally, I don't see any errors, but why isn't it working? Thanks in advance 🙏 

update: I tried the whole node-gyp rebuild thing and that doesn't work for me either
![image](https://github.com/carsondarling/bcrypt-cli/assets/19779234/9e9ae3c4-8db2-4af7-9446-a2de02e55319)

**Comment by SSTPIERRE2** [comment]
I'm going to suggest instead using one of the many online bcrypt generators such as https://bcrypt.online/ works perfectly for my needs. I just needed to manually generate a hash from a string.

**Comment by carsondarling** [comment]
It's possible that the issue you were having had to do with escaping strings in your shell. Because Bcrypt uses `$` as a delimiter, the shell will attempt to replace sections of the hashed value. Proper quoting or escaping of the hashed value should allow it to work.

For example:
```
> bcrypt test
$2b$10$ysLpI0iFrHs3SIG0wDF4qu6vV4x6cwvlCU5zp2EdFOLSjBHqbn3Mm%

> debcrypt $2b$10$ysLpI0iFrHs3SIG0wDF4qu6vV4x6cwvlCU5zp2EdFOLSjBHqbn3Mm test
Hash does not match.

> debcrypt '$2b$10$ysLpI0iFrHs3SIG0wDF4qu6vV4x6cwvlCU5zp2EdFOLSjBHqbn3Mm' test
Match!
